name: green_steps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  firebase_core: ^2.25.4
  firebase_storage: ^11.4.2
  cloud_firestore: ^4.13.0
  path_provider: ^2.1.5
  flutter_local_notifications: 19.0.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/