name: "Eco Log Activity"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest


    steps: 
      uses: actions/checkout@v3

      uses: subosito/futter-action@v2
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
      run: flutter analyze

      - name: Build APK
      run: flutter build apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

